#!/bin/bash

if test -x "/usr/bin/apt"; then
    # we must manually set permissions on apt/deb based system because deb’s have no mechanism for permission.
    chown root:nobody /usr/sbin/suexec
    chmod 4755 /usr/sbin/suexec
    setcap cap_setgid,cap_setuid+ep /usr/sbin/suexec
fi

# We do not START these services here because we
#   depend on the universal hook to do that for us.
/bin/systemctl enable httpd.service >/dev/null 2>&1
